---
deployment:
  tasks:
    # 1️⃣ Xác định thư mục đích (nơi app đang chạy thật)
    - export DEPLOYPATH=/home/xnzbgatp/backend-nestjs

    # 2️⃣ Kích hoạt môi trường Node.js đúng phiên bản
    - source /home/xnzbgatp/nodevenv/backend-nestjs/20/bin/activate

    # 3️⃣ Cài dependency (nếu cần, bỏ qua devDependencies)
    - cd /home/xnzbgatp/repositories/backend-nestjs
    - npm install

    # 4️⃣ Build lại NestJS (từ TypeScript sang JavaScript)
    - npm run build

    # 5️⃣ Copy file build & cấu hình sang thư mục deploy thật
    - /bin/cp -R dist $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp -R node_modules $DEPLOYPATH/
    - /bin/cp -R src $DEPLOYPATH/
